version: 2.1
job: 
  test:
    steps:
      - checkout
      - run:
        command: cd frontend && npm install
      - run:
        command: cd frontend && npm test
# orbs:
#   node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - test
      # - node/test
      
